# .pre-commit-config.yaml
repos:
  # Standard hooks for file health
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use a recent, stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Ruff for lightning-fast linting AND formatting.
  # This one tool replaces black, isort, and flake8.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5  # Use a recent, stable version
    hooks:
      # Run the linter to find and automatically fix issues.
      - id: ruff
        args: [--fix, --show-fixes]
      # Run the formatter to ensure consistent code style.
      - id: ruff-format

  # Mypy for static type checking (Ruff does not do this)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0 # Use a recent, stable version
    hooks:
      - id: mypy
        # Your existing dependencies and args are good.
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports]

# --- DELETED TOOLS ---
# The following tools are no longer needed because their functionality is
# now handled by Ruff, resulting in a simpler and faster pre-commit setup.
#
# - repo: https://github.com/psf/black (Replaced by `ruff-format`)
# - repo: https://github.com/pycqa/isort (Replaced by `ruff --fix`)
# - repo: https://github.com/pycqa/flake8 (Replaced by `ruff`)
