[project]
name = "vivre"
version = "0.1.0"
description = "A Python library for machine learning and corpus linguistics"
authors = [
    {name = "Aniket Dixit",email = "aniketdixit00.ani@gmail.com"}
]
readme = "README.md"
requires-python = "^3.9"
dependencies = [
    "requests (>=2.32.4,<3.0.0)",
    "pytest (>=8.4.1,<9.0.0)"
]

[tool.poetry]
packages = [
    {include = "vivre"}
]

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
flake8 = "^7.3.0"
mypy = "^1.17.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
