name: Update Dependencies

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Check for outdated dependencies
      id: check
      run: |
        poetry show --outdated --format json > outdated.json
        if [ -s outdated.json ]; then
          echo "has_updates=true" >> $GITHUB_OUTPUT
        else
          echo "has_updates=false" >> $GITHUB_OUTPUT
        fi

    - name: Update dependencies
      if: steps.check.outputs.has_updates == 'true'
      run: |
        poetry update
        poetry export -f requirements.txt --output requirements.txt --without-hashes

    - name: Create Pull Request
      if: steps.check.outputs.has_updates == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: update dependencies'
        body: |
          This PR updates outdated dependencies.

          Auto-generated by GitHub Actions.
        branch: chore/update-dependencies
        delete-branch: true
