name: Security

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --only=main,dev

    - name: Run security checks
      run: python scripts/security_check.py

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/owasp-top-ten
        output-format: sarif
        output-file: semgrep-results.sarif

    - name: Check if Semgrep results exist
      id: check-semgrep
      run: |
        if [ -f semgrep-results.sarif ] && [ -s semgrep-results.sarif ]; then
          echo "has_results=true" >> $GITHUB_OUTPUT
        else
          echo "has_results=false" >> $GITHUB_OUTPUT
        fi

    - name: Upload Semgrep results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && steps.check-semgrep.outputs.has_results == 'true'
      with:
        sarif_file: semgrep-results.sarif
